version: "3.7"
services:
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/volumes/traefik:/etc/traefik
      - ${USERDIR}/volumes/shared:/shared
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik_proxy
    environment:
      - OVH_ENDPOINT=${OVH_ENDPOINT}
      - OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}
      - OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
    labels:
      - traefik.enable=true
      - traefik.backend=traefik
      - traefik.frontend.auth.basic.usersFile=/etc/traefik/.htpasswd
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.rule=Host:traefik.${DOMAINNAME}
      - traefik.port=8080
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.contentTypeNosniff=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.SSLHost=${DOMAINNAME}
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.headers.frameDeny=true
networks:
  traefik_proxy:
    name: traefik_proxy
